name: Update README
on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Last updated: $(date)" >> README.md
      - uses: EndBug/add-and-commit@v9
        with:
          message: "Update README timestamp"